---

- name: check for existing satellite install
  shell: hammer ping
  register: hammer_output
  changed_when: false
  failed_when: false
  check_mode: false
  ignore_errors: true

- name: Read Install Options
  ansible.builtin.slurp:
    src: /root/satellite/options
  when:
    - satellite_options_file.skipped is undefined
  register: satellite_options

- name: run the satellite installer
  shell: "satellite-installer --scenario satellite {{ satellite_options.content | b64decode | default('') }}"
  register: satellite_installer_output
  when:
    - "'Failed to open TCP connection' in hammer_output.stderr or (satellite_options_file.changed is defined and satellite_options_file.changed)"
